name: Check

permissions:
  contents: read

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - "main"

jobs:
  check:
    uses: TerakomariGandesblood/github-workflows/.github/workflows/markdown-check.yml@main
    with:
      markdown_globs: "content/posts/*.md"
